cookie:
  expiry_days: 30
  name: stauth
  key: $2b$12$nTFmaKwIjaLojO2ZebllWu4oIRRD8cgQdx2V3OF7woxE5sGUqVlmG

credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin
      password: $2b$12$JLl6P92TQqtwbjbNYO3kGeS9imrwY3WReiebEs9Pny1kAKxuBHyti
      role: admin
    jorge:
      area: Hollenbeck
      email: jorge
      name: jorge
      password: $2b$12$O79kUF2IYVz7U5lC1ClazOdA.7aKJm8sRLgd4hgDu9OotTb2oied2
      role: admin
    user1:
      area: Hollywood
      email: user@example.com
      name: Usuario Regular
      password: $2b$12$JLl6P92TQqtwbjbNYO3kGeS9imrwY3WReiebEs9Pny1kAKxuBHyti
      role: user
preauthorized:
  usernames:
    - admin
    - jorge

